// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4edOFp9P_Puq0ugLyC73y-FccWY3d6Y4',
    appId: '1:199876414336:web:ed086886105c8699d50f65',
    messagingSenderId: '199876414336',
    projectId: 'task-manager-778a7',
    authDomain: 'task-manager-778a7.firebaseapp.com',
    storageBucket: 'task-manager-778a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIMfd5m8iIovVeT6O2Vy4RSy9UiPffw8',
    appId: '1:199876414336:android:ef47137477800f3fd50f65',
    messagingSenderId: '199876414336',
    projectId: 'task-manager-778a7',
    storageBucket: 'task-manager-778a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5DreX-uhI-4Vx0EV6ro7xc8OIgxMimg',
    appId: '1:199876414336:ios:60eeb441f1e464b1d50f65',
    messagingSenderId: '199876414336',
    projectId: 'task-manager-778a7',
    storageBucket: 'task-manager-778a7.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5DreX-uhI-4Vx0EV6ro7xc8OIgxMimg',
    appId: '1:199876414336:ios:60eeb441f1e464b1d50f65',
    messagingSenderId: '199876414336',
    projectId: 'task-manager-778a7',
    storageBucket: 'task-manager-778a7.appspot.com',
    iosBundleId: 'com.example.taskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4edOFp9P_Puq0ugLyC73y-FccWY3d6Y4',
    appId: '1:199876414336:web:4440f69f3ec3c2e1d50f65',
    messagingSenderId: '199876414336',
    projectId: 'task-manager-778a7',
    authDomain: 'task-manager-778a7.firebaseapp.com',
    storageBucket: 'task-manager-778a7.appspot.com',
  );
}
